#include "../../knowledge/knowledge.h"

const char *vocab[VOCAB_SIZE] = {
    "the","a","is","it","was","I","you","we","they","he","she","and","or","but",
    "not","no","yes","what","why","how","when","where","who","if","then","also",
    "very","quite","maybe","probably","never","always","sometimes","often",
    "do","did","does","have","has","had","will","would","could","should","can",
    "be","been","get","got","go","went","come","came","see","know","think",
    "say","want","need","look","find","make","take","give","use","keep","feel",
    "thing","man","woman","child","way","day","year","time","work","life","hand",
    "part","place","case","week","point","number","money","lot","right","word",
    "problem","plan","group","game","room","form","home","power","area","order",
    "face","level","heart","mind","result","age","voice","language","science",
    "computer","data","network","process","function","error","signal","energy",
    "light","dark","color","sound","air","fire","earth","space","force","wave",
    "node","loop","table","key","value","string","object","type","true","false",
    "zero","one","two","three","four","five","hundred","thousand","million",
    "good","bad","new","old","high","low","large","small","long","short","big",
    "right","wrong","same","different","real","best","free","strong","clear",
    "hard","simple","possible","rather","far","hot","cold","fast","slow","deep",
    "broken","dead","lost","warm","bright","quiet","strange","beautiful","random",
    "okay","fine","well","just","only","even","still","already","yet","again",
    "now","then","here","there","back","away","down","up","over","under","after",
    "before","since","while","although","because","so","however","therefore",
    "actually","literally","honestly","clearly","obviously","exactly","simply",
    "really","quite","almost","enough","too","very","more","most","much","many",
    "some","any","all","both","each","every","few","several","another","next",
    "hmm","uh","oh","ah","well","okay","sure","fine","yes","no","nope","wait",
    "indeed","perhaps","certainly","absolutely","definitely","apparently",
    "gradually","entirely","completely","mostly","partly","nearly","roughly",
    "approximately","specifically","generally","particularly","especially",
    "quickly","slowly","carefully","easily","directly","eventually","finally",
    "immediately","normally","originally","previously","recently","suddenly",
    "typically","usually","constantly","currently","frequently","naturally",
    "personally","potentially","possibly","probably","regularly","relatively",
    "significantly","successfully","technically","effectively","officially",
    "rapidly","seriously","similarly","slightly","smoothly","totally","truly",
    "ultimately","virtually","completely","correctly","differently","equally",
    "essentially","explicitly","fairly","formally","fully","generally","honestly",
    "increasingly","individually","internally","largely","literally","locally",
    "logically","meaningfully","mentally","merely","moderately","notably",
    "obviously","openly","partially","perfectly","positively","purely","randomly",
    "reasonably","reliably","remarkably","repeatedly","sharply","silently",
    "simultaneously","spontaneously","statistically","structurally","substantially",
    "sufficiently","symbolically","systematically","theoretically","thoroughly",
    "transparently","trivially","uniquely","universally","unusually","verbally",
    "visually","broadly","collectively","commercially","comparatively","critically",
    "culturally","digitally","drastically","dynamically","economically","emotionally",
    "empirically","experimentally","politically","practically","precisely","primarily",
    "properly","publicly","sensibly","sequentially","solidly","spatially",
    "structurally","voluntarily","chemically","mechanically","minimally","mutually",
    "independently","collaboratively","fundamentally","historically","strategically",
    "analytically","deliberately","continuously","alternatively","comprehensively",
    "consequently","simultaneously","unconditionally","systematically","extensively",
    "progressively","consistently","persistently","spontaneously","interestingly",
    "surprisingly","unfortunately","additionally","approximately","substantially",
    "significantly","correspondingly","proportionally","exponentially","recursively",
    "iteratively","asynchronously","synchronously","probabilistically","statistically",

    "algorithm","variable","constant","parameter","argument","pointer","reference",
    "array","struct","enum","typedef","malloc","realloc","callback","thread",
    "mutex","semaphore","deadlock","race","condition","volatile","register",
    "inline","recursive","iterative","binary","hexadecimal","octal","bitwise",
    "overflow","underflow","truncation","precision","floating","integer","unsigned",
    "signed","static","extern","volatile","const","macro","header","library",
    "linker","compiler","assembler","bytecode","opcode","instruction","register",
    "pipeline","cache","memory","heap","stack","queue","tree","graph","hash",
    "sort","search","insert","delete","update","query","index","schema","table",
    "column","row","constraint","transaction","commit","rollback","foreign",
    "primary","unique","null","boolean","char","byte","float","double","long",
    "short","void","auto","break","case","continue","default","else","for",
    "goto","switch","while","return","sizeof","typedef","union","unsigned",

    "server","client","request","response","endpoint","middleware","router",
    "controller","model","view","template","render","route","session","cookie",
    "token","authentication","authorization","encryption","decryption","hashing",
    "certificate","protocol","socket","port","domain","DNS","HTTP","HTTPS","TCP",
    "UDP","API","REST","JSON","XML","HTML","CSS","JavaScript","Python","Java",
    "Rust","Swift","Kotlin","Ruby","PHP","SQL","NoSQL","MongoDB","Redis","Docker",
    "Kubernetes","Git","branch","merge","commit","push","pull","clone","fork",

    "window","screen","pixel","resolution","display","monitor","keyboard","mouse",
    "button","click","scroll","drag","drop","menu","toolbar","modal","popup",
    "dialog","notification","alert","warning","info","success","failure","pending",
    "loading","progress","complete","download","upload","install","uninstall",
    "configure","setup","deploy","release","version","patch","update","upgrade",
    "rollback","backup","restore","sync","async","await","promise","future",

    "molecule","atom","electron","proton","neutron","photon","quantum","wave",
    "particle","frequency","wavelength","amplitude","spectrum","radiation","decay",
    "fusion","fission","isotope","catalyst","reaction","compound","element","bond",
    "crystal","polymer","protein","enzyme","chromosome","genome","mutation","cell",
    "nucleus","membrane","organism","species","evolution","extinction","fossil",
    "sediment","volcano","earthquake","tsunami","glacier","continent","atmosphere",
    "climate","weather","hurricane","tornado","drought","flood","ecosystem",

    "democracy","republic","parliament","congress","senate","court","justice",
    "constitution","amendment","legislation","regulation","treaty","alliance",
    "sovereignty","diplomacy","sanction","embargo","tariff","trade","commerce",
    "inflation","deflation","recession","depression","surplus","deficit","budget",
    "revenue","expenditure","taxation","subsidy","monopoly","oligarchy","capitalism",
    "socialism","communism","feudalism","monarchy","anarchy","revolution","reform",

    "philosophy","metaphysics","epistemology","ontology","ethics","aesthetics",
    "logic","rhetoric","dialectic","syllogism","axiom","theorem","hypothesis",
    "postulate","conjecture","proof","refutation","paradox","dilemma","fallacy",
    "consciousness","perception","cognition","intuition","rationality","empiricism",
    "determinism","causality","teleology","phenomenology","existentialism","nihilism",

    "cathedral","monastery","temple","mosque","synagogue","pagoda","shrine","altar",
    "pillar","arch","dome","vault","buttress","gargoyle","facade","portico",
    "kitchen","bathroom","bedroom","corridor","staircase","elevator","basement",
    "attic","balcony","terrace","garage","warehouse","factory","laboratory",
    "hospital","pharmacy","clinic","ambulance","surgery","diagnosis","symptom",
    "vaccine","antibiotic","therapy","treatment","prescription","dosage","capsule",

    "guitar","piano","violin","drums","trumpet","flute","saxophone","harmonica",
    "orchestra","symphony","concerto","sonata","melody","harmony","rhythm","tempo",
    "chord","octave","scale","pitch","tone","bass","treble","soprano","baritone",
    "painting","sculpture","canvas","brush","palette","portrait","landscape","mural",
    "sketch","watercolor","oil","pastel","charcoal","gallery","museum","exhibition",

    "breakfast","lunch","dinner","dessert","appetizer","salad","soup","sandwich",
    "pasta","rice","bread","butter","cheese","sauce","ingredient","recipe","chef",
    "oven","stove","microwave","refrigerator","freezer","blender","spatula","fork",
    "knife","spoon","plate","bowl","cup","glass","napkin","tablecloth","menu",

    "mountain","valley","river","ocean","lake","island","peninsula","desert","forest",
    "jungle","prairie","tundra","canyon","cliff","cave","waterfall","spring","creek",
    "harbor","coast","shore","beach","reef","lagoon","delta","basin","plateau",

    "el","la","los","las","un","una","es","fue","son","era","yo","tú","él","ella",
    "nosotros","ellos","y","o","pero","no","sí","qué","por","cómo","cuándo",
    "dónde","quién","si","entonces","también","muy","quizás","nunca","siempre",
    "hacer","tener","ser","estar","ir","venir","ver","saber","pensar","querer",
    "cosa","hombre","mujer","día","año","tiempo","trabajo","vida","mundo","casa",
    "parte","lugar","número","dinero","palabra","problema","grupo","forma","poder",
    "mente","corazón","voz","ciencia","datos","error","señal","energía","luz",
    "oscuro","color","sonido","tierra","espacio","fuerza","bueno","malo","nuevo",
    "viejo","grande","pequeño","largo","corto","mismo","diferente","real","libre",
    "claro","difícil","posible","rápido","lento","profundo","roto","perdido","cálido",
    "tranquilo","extraño","hermoso","aleatorio","bien","solo","incluso","todavía",
    "ahora","aquí","allí","arriba","abajo","antes","después","aunque","porque",
    "realmente","completamente","principalmente","generalmente","especialmente",
    "verdad","persona","ciudad","país","gobierno","cultura","historia","música",
    "tecnología","sistema","proceso","función","resultado","nivel","orden","cara",

    "le","la","les","un","une","est","était","sont","je","tu","il","elle","nous",
    "ils","elles","et","ou","mais","non","oui","quoi","pourquoi","comment","quand",
    "faire","avoir","être","aller","venir","voir","savoir","penser","vouloir",
    "chose","homme","femme","jour","année","temps","travail","vie","monde","maison",
    "partie","place","nombre","argent","mot","problème","groupe","forme","pouvoir",
    "esprit","coeur","voix","science","données","erreur","signal","énergie","lumière",
    "sombre","couleur","son","air","feu","terre","espace","force","bon","mauvais",
    "nouveau","vieux","grand","petit","long","court","même","différent","réel","libre",
    "clair","difficile","possible","rapide","lent","profond","brisé","perdu","chaud",
    "calme","étrange","beau","aléatoire","bien","seulement","encore","déjà","maintenant",
    "ici","là","après","avant","parce que","donc","vraiment","complètement",
    "généralement","particulièrement","surtout","finalement","évidemment","certainement",
    "probablement","naturellement","rapidement","directement","facilement","clairement",

    "die","der","das","ein","eine","ist","war","sind","ich","du","er","sie","wir",
    "und","oder","aber","nicht","ja","nein","was","warum","wie","wann","wo","wer",
    "machen","haben","sein","gehen","kommen","sehen","wissen","denken","wollen",
    "Ding","Mann","Frau","Tag","Jahr","Zeit","Arbeit","Leben","Welt","Haus",
    "Teil","Ort","Zahl","Geld","Wort","Problem","Gruppe","Form","Kraft","Geist",
    "Herz","Stimme","Wissenschaft","Daten","Fehler","Signal","Energie","Licht",
    "dunkel","Farbe","Ton","Luft","Feuer","Erde","Raum","gut","schlecht","neu",
    "alt","groß","klein","lang","kurz","gleich","verschieden","echt","frei",
    "klar","schwer","möglich","schnell","langsam","tief","kaputt","verloren",
    "warm","ruhig","seltsam","schön","zufällig","gut","nur","noch","schon",
    "jetzt","hier","dort","oben","unten","nach","vor","obwohl","weil","also",
    "wirklich","vollständig","allgemein","besonders","schließlich","offensichtlich",
    "sicher","wahrscheinlich","natürlich","schnell","direkt","leicht","klar",

    "это","не","да","нет","что","как","где","кто","когда","почему","если","то",
    "быть","иметь","делать","идти","знать","думать","говорить","видеть","хотеть",
    "вещь","человек","день","год","время","работа","жизнь","мир","дом","часть",
    "место","число","деньги","слово","проблема","группа","сила","ум","сердце",
    "голос","данные","ошибка","свет","тьма","звук","земля","пространство","хороший",
    "плохой","новый","старый","большой","маленький","длинный","короткий","свободный",
    "реальный","ясный","сложный","возможный","быстрый","медленный","глубокий",
    "теплый","тихий","странный","красивый","случайный","здесь","там","после",
    "перед","потому","что","однако","действительно","полностью","обычно","особенно",
    "наконец","очевидно","вероятно","естественно","быстро","прямо","легко",

    "il","lo","la","i","gli","le","un","è","era","sono","io","tu","lui","lei",
    "noi","loro","e","o","ma","non","sì","no","cosa","perché","come","quando",
    "fare","avere","essere","andare","venire","vedere","sapere","pensare","volere",
    "cosa","uomo","donna","giorno","anno","tempo","lavoro","vita","mondo","casa",
    "parte","posto","numero","denaro","parola","problema","gruppo","forma","potere",
    "mente","cuore","voce","scienza","dati","errore","segnale","energia","luce",
    "buio","colore","suono","aria","fuoco","terra","spazio","forza","buono",
    "cattivo","nuovo","vecchio","grande","piccolo","lungo","corto","stesso",
    "diverso","reale","libero","chiaro","difficile","possibile","veloce","lento",
    "profondo","rotto","perso","caldo","quieto","strano","bello","casuale",

    "o","a","os","as","um","uma","é","foi","são","eu","tu","ele","ela","nós",
    "eles","e","ou","mas","não","sim","que","por","como","quando","onde","quem",
    "fazer","ter","ser","estar","ir","vir","ver","saber","pensar","querer",
    "coisa","homem","mulher","dia","ano","tempo","trabalho","vida","mundo","casa",
    "parte","lugar","número","dinheiro","palavra","problema","grupo","forma","poder",
    "mente","coração","voz","ciência","dados","erro","sinal","energia","luz",
    "escuro","cor","som","ar","fogo","terra","espaço","força","bom","mau","novo",
    "velho","grande","pequeno","longo","curto","mesmo","diferente","real","livre",
    "claro","difícil","possível","rápido","lento","profundo","quebrado","perdido",

    "ja","nie","tak","co","jak","gdzie","kto","kiedy","dlaczego","jeśli","to",
    "robić","mieć","być","iść","wiedzieć","myśleć","chcieć","widzieć","mówić",
    "rzecz","człowiek","dzień","rok","czas","praca","życie","świat","dom","część",
    "miejsce","liczba","pieniądze","słowo","problem","grupa","forma","siła","umysł",
    "serce","głos","dane","błąd","sygnał","energia","światło","ciemny","kolor",
    "dźwięk","ziemia","przestrzeń","dobry","zły","nowy","stary","duży","mały",
    "długi","krótki","ten sam","inny","prawdziwy","wolny","jasny","trudny","możliwy",

    "det","en","ett","är","var","och","eller","men","inte","ja","nej","vad",
    "varför","hur","när","var","vem","om","göra","ha","vara","gå","veta","tänka",
    "sak","man","dag","år","tid","arbete","liv","värld","del","plats","nummer",
    "pengar","ord","problem","grupp","form","kraft","hjärta","röst","ljus","mörk",
    "färg","ljud","jord","rymd","bra","dålig","ny","gammal","stor","liten","lång",

    "bir","bu","o","ve","ya","ama","değil","evet","hayır","ne","neden","nasıl",
    "ne zaman","nerede","kim","eğer","yapmak","olmak","gitmek","bilmek","düşünmek",
    "şey","adam","kadın","gün","yıl","zaman","iş","hayat","dünya","ev","yer",
    "sayı","para","kelime","sorun","grup","güç","akıl","kalp","ses","ışık","karanlık",
    "renk","ses","hava","ateş","toprak","uzay","iyi","kötü","yeni","eski","büyük",

    "ある","ない","何","どう","いつ","どこ","誰","もし","する","ある","いく","くる","みる","知る","思う",
    "もの","人","日","年","時間","仕事","生活","世界","場所","数","言葉","問題","力","心","声",
    "光","暗","色","音","空","火","地球","宇宙","良い","悪い","新しい","古い","大きい","小さい",

    "na","ya","si","hindi","oo","ano","bakit","paano","kailan","saan","sino",
    "gawin","mayroon","pumunta","malaman","isipin","bagay","tao","araw","taon",
    "oras","trabaho","buhay","mundo","lugar","numero","salita","problema","grupo",

    "är","inte","ja","nej","vad","hur","när","var","vem","göra","vara","gå",
    "dag","tid","värld","plats","ord","kraft","hjärta","ljus","mörk","bra","dålig",

    "eğer","ama","ve","bu","şey","ne","nasıl","neden","iyi","kötü","büyük","küçük",
    "zaman","yer","ses","güç","yeni","eski","hızlı","yavaş","derin","kırık","kayıp",

    "kwamba","ni","na","au","lakini","ndiyo","hapana","nini","kwa","jinsi","lini",
    "wapi","nani","kama","kufanya","kuwa","kwenda","kujua","kufikiria","kitu",
    "mtu","siku","mwaka","wakati","kazi","maisha","dunia","mahali","nambari","nguvu",

    "er","ist","hat","wird","kann","muss","soll","darf","mag","lassen","bleiben",
    "kommen","gehen","stehen","liegen","sitzen","halten","bringen","nehmen","geben",
    "zeigen","spielen","laufen","schreiben","lesen","sprechen","hören","verstehen",
    "kennen","lernen","arbeiten","helfen","suchen","finden","kaufen","verkaufen",

    "hace","tiene","puede","debe","quiere","viene","va","da","pone","toma","sabe",
    "habla","escribe","lee","escucha","entiende","conoce","aprende","trabaja",
    "ayuda","busca","encuentra","compra","vende","mueve","vive","cree","cambia",

    "fait","a","peut","doit","veut","vient","va","donne","prend","sait","parle",
    "écrit","lit","écoute","comprend","connaît","apprend","travaille","aide",
    "cherche","trouve","achète","vend","bouge","vit","croit","change","joue",

    "undefined","null","NaN","void","error","return","break","continue","switch",
    "while","loop","stack","overflow","timeout","crash","reboot","kernel","panic",
    "syntax","exception","runtime","compile","debug","trace","memory","leak","cache",
    "flush","buffer","overflow","segfault","interrupt","signal","socket","packet",

    "entropy","paradox","recursion","iteration","abstraction","encapsulation",
    "polymorphism","inheritance","mutation","variation","selection","adaptation",
    "equilibrium","resonance","oscillation","perturbation","bifurcation","chaos",
    "emergence","complexity","topology","manifold","gradient","divergence","curl",
    "eigenvalue","tensor","matrix","vector","scalar","integral","derivative",
    "probability","distribution","variance","correlation","regression","entropy",

    "wirklich","eigentlich","vielleicht","wahrscheinlich","möglicherweise","offenbar",
    "anscheinend","scheinbar","angeblich","vermutlich","tatsächlich","jedenfalls",
    "übrigens","allerdings","immerhin","trotzdem","dennoch","doch","schon","eben",

    "peut-être","probablement","certainement","évidemment","apparemment","sûrement",
    "vraiment","totalement","simplement","seulement","juste","même","encore","déjà",
    "toujours","jamais","parfois","souvent","rarement","beaucoup","peu","très","trop",

    "quizás","tal vez","probablemente","seguramente","evidentemente","aparentemente",
    "realmente","totalmente","simplemente","solo","incluso","todavía","ya","siempre",
    "nunca","a veces","frecuentemente","raramente","mucho","poco","muy","demasiado",

    "конечно","наверное","возможно","очевидно","действительно","совершенно","просто",
    "только","даже","ещё","уже","всегда","никогда","иногда","часто","редко","много",

    "ovviamente","probabilmente","certamente","evidentemente","apparentemente",
    "davvero","completamente","semplicemente","solo","anche","ancora","già","sempre",
    "mai","a volte","spesso","raramente","molto","poco","troppo","abbastanza",

    "kanske","förmodligen","säkert","självklart","uppenbarligen","egentligen",
    "verkligen","helt","enkelt","bara","även","fortfarande","redan","alltid",
    "aldrig","ibland","ofta","sällan","mycket","lite","för","tillräckligt",

    "belki","muhtemelen","kesinlikle","açıkça","gerçekten","tamamen","sadece",
    "bile","hâlâ","zaten","her zaman","hiçbir zaman","bazen","sık sık","nadiren",

    "algorithm","bandwidth","byte","cloud","daemon","ethernet","firmware",
    "gigabyte","hash","index","javascript","kilobyte","latency","malware",
    "namespace","opcode","pipeline","query","router","schema","thread",
    "uptime","virtual","webhook","xor","yaml","zombie",
    "asteroid","bacteria","catalyst","dinosaur","electron","fossil",
    "gravity","hemisphere","isotope","jupiter","kinetic","lava",
    "molecule","neutron","orbit","photon","quasar","reactor",
    "supernova","telescope","uranium","volcano","wavelength","xenon",
    "avocado","baguette","croissant","dumpling","espresso","falafel",
    "goulash","hummus","ice cream","jelly","kebab","lasagna",
    "mango","noodle","omelette","pancake","quinoa","ramen",
    "sashimi","tortilla","udon","vanilla","waffle","yogurt",
    "accordion","banjo","cello","drum","euphonium","flute",
    "guitar","harmonica","instrument","jazz","keyboard","lute",
    "mandolin","note","orchestra","piano","quartet","rhythm",
    "saxophone","trumpet","ukulele","violin","waltz","xylophone",
    "archery","baseball","cricket","diving","equestrian","fencing",
    "golf","hockey","ice skating","javelin","karate","lacrosse",
    "marathon","netball","obstacle","polo","quidditch","rugby",
    "soccer","tennis","unicycle","volleyball","wrestling","yachting",
    "antelope","buffalo","chameleon","dolphin","elephant","flamingo",
    "gorilla","hedgehog","iguana","jaguar","kangaroo","lemur",
    "manatee","narwhal","octopus","penguin","quail","raccoon",
    "salamander","toucan","urchin","vulture","walrus","yak",
    "aqueduct","buttress","colonnade","dome","facade","gargoyle",
    "hallway","ivory","joist","keystone","lintel","minaret",
    "nave","obelisk","parapet","rotunda","spire","turret",
    "vault","windmill","ziggurat","amphitheater","basilica","citadel",
    "archipelago","bayou","canyon","delta","estuary","fjord",
    "glacier","harbor","isthmus","jungle","knoll","lagoon",
    "meadow","narrows","oasis","peninsula","ravine","steppe",
    "tundra","underwater","valley","wetland","zenith","horizon",
    "azure","bronze","crimson","denim","emerald","fuchsia",
    "gold","haze","indigo","jade","khaki","lavender",
    "maroon","navy","ochre","periwinkle","ruby","sapphire",
    "tangerine","umber","vermillion","wheat","sapphire","zinc",
    "anchor","beacon","compass","driftwood","ember","forge",
    "geyser","harpoon","inkwell","journal","kite","lantern",
    "mirror","needle","ornament","prism","quill","riddle",
    "scroll","tapestry","umbrella","veil","wand","zephyr",
    "alchemy","Byzantine","calligraphy","dynasty","epoch","folklore",
    "gladiator","heraldry","inquisition","juggernaut","knight","legion",
    "monastery","nomad","oracle","pilgrim","questionnaire","renaissance",
    "samurai","troubadour","utopia","viking","wizard","dynasty",

    "backspace","capslock","clipboard","desktop","emoji","favicon",
    "glitch","hotkey","iframe","jailbreak","keyframe","localhost",
    "middleware","notification","offline","pixel","quicksort","render",
    "stylesheet","thumbnail","unicode","viewport","widget","xpath",
    "boolean","callback","decorator","endpoint","frontend","gateway",
    "handler","iterator","json","lambda","module","observable",
    "prototype","reducer","singleton","transpiler","unittest","validator",
    "wildcard","wrapper","zigzag","yonder",
};
