#include "../../knowledge/knowledge.h"

const char *v2_think_connectors[] = {
    "hmm", "wait", "actually", "no", "but", "so", "therefore",
    "unless", "considering", "however", "indeed", "perhaps",
    "fundamentally", "interestingly", "okay", "right", "well",
    "let me think", "on second thought", "basically", "clearly",
    "obviously", "I recall", "it seems", "the thing is",
    "now", "then again", "hold on", "yes", "ah",
    "see", "look", "anyway", "though", "yet", "still",
    "huh", "aha", "oh", "alright", "true", "fair",
    "granted", "surely", "apparently", "meanwhile", "regardless",
    "notably", "importantly", "curiously", "oddly", "strangely",
    "funny enough", "thing is", "point is", "fact is",
    "precisely", "naturally", "hence", "likewise", "furthermore",
    "consequently", "admittedly", "arguably", "supposedly", "technically",
    "frankly", "truthfully", "realistically", "theoretically", "evidently",
    "mind you", "come to think of it", "if I recall", "in hindsight",
    "upon reflection"
};
const int v2_think_connectors_n = 76;

const char *v2_think_fillers[] = {
    "this means", "which implies", "if we consider",
    "from what I know", "that reminds me", "in other words",
    "the key point is", "wait no", "scratch that",
    "going back to", "the real question is",
    "let me reconsider", "I think", "so basically",
    "putting it together", "on reflection",
    "meaning", "implying", "essentially", "roughly",
    "so then", "and yet", "but then", "still though",
    "which means", "come to think", "now that I think",
    "given that", "assuming", "supposedly", "apparently",
    "seems like", "looks like", "feels like",
    "that said", "to clarify", "in short", "in a sense",
    "broadly speaking", "for what it's worth", "if anything",
    "the point being", "as it turns out", "believe it or not",
    "long story short", "in my experience", "either way",
    "bottom line", "all things considered", "strictly speaking"
};
const int v2_think_fillers_n = 50;

const char *v2_knowledge_intros[] = {
    "right",
    "oh",
    "so",
    "yes",
    "ah",
    "hmm",
    "okay",
    "well",
    "sure",
    "true",
    "wait",
    "see",
    "oh right",
    "ah yes",
    "I recall",
    "oh wait",
    "got it",
    "I know",
    "right so",
    "hm okay",
    "well yes",
    "aha",
    "indeed",
    "clearly",
    "of course",
    "actually",
    "listen",
    "basically",
    "fun fact",
    "oh yeah",
    "that said",
    "now then",
    "look",
    "yo",
    "yep",
    "real talk",
    "here's the thing",
    "I mean",
    "word",
    "so yeah"
};
const int v2_knowledge_intros_n = 40;

const char *v2_opinion_think_phrases[] = {
    "honestly",
    "interesting",
    "fascinating",
    "huh",
    "true",
    "fair",
    "nice",
    "wow",
    "wild",
    "bold",
    "cool",
    "deep",
    "neat",
    "oh wow",
    "so true",
    "big deal",
    "no way",
    "makes sense",
    "I agree",
    "that tracks",
    "good point",
    "fair enough",
    "valid",
    "solid",
    "real",
    "based",
    "yikes",
    "sheesh",
    "tough",
    "huge",
    "massive",
    "crazy",
    "legit",
    "absurd",
    "brilliant",
    "genius",
    "spicy",
    "relatable",
    "underrated",
    "overrated",
    "hard agree",
    "can't argue",
    "well said",
    "spot on",
    "couldn't agree more",
    "seriously though",
    "that's a take",
    "totally"
};
const int v2_opinion_think_phrases_n = 48;
